version: '3.8'

services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf

  alpine:
    image: alpine
    command: echo "Hello from Alpine!"
    
  test:
    image: alpine
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "apk add --no-cache curl && sh ./test.sh"
