name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Change directory to root
      run: cd $GITHUB_WORKSPACE

    - name: Set up Docker Compose
      run: sudo apt-get -y install docker-compose

    - name: Build and run services
      run: docker-compose -f $GITHUB_WORKSPACE/docker-compose.yml up -d

    - name: Run tests
      run: docker-compose -f $GITHUB_WORKSPACE/docker-compose.yml run test

    - name: Clean up
      run: docker-compose -f $GITHUB_WORKSPACE/docker-compose.yml down